name: lab007 Terraform CI

on:
  push:
    paths:
      - 'lab007-cicd/**'
    branches: [ main ]

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab007-cicd

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
